apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: naive-bayes-training-v5
  annotations:
    scenarios.ai.sap.com/description: "naive-bayes training Pipeline-v5"
    scenarios.ai.sap.com/name: "naive-bayes-v5"
    executables.ai.sap.com/description: "naive-bayes model-v5"
    executables.ai.sap.com/name: "naive-bayes-training-v5"
  labels:
    scenarios.ai.sap.com/id: "naive-bayes-v5"
    ai.sap.com/version: "1.0.0"
spec:
  entrypoint: training-pipeline
  templates:
    - name: training-pipeline
      steps:
        - - name: train
            template: train-step
 
    - name: train-step
      metadata:
        labels:
          ai.sap.com/resourcePlan: starter
      container:
        image: docker.io/rahulcruze786/ml_training_model:v1.10
        command: ["python"]
        args:
          - "trainer.py"
        env:
          - name: MODEL_DIR
            value: "/tmp/models"
          - name: MODEL_DIR1
            value: "/tmp/models1"
      outputs:
        artifacts:
          - name: model-output
            globalName: multinomialNB
            path: /tmp/models
            type: model                  # ← added
            archive:
              none: {}
 
          - name: model-output1
            globalName: multinomialNB1
            path: /tmp/models1
            type: model                  # ← added
            archive:
              none: {}
