apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: naive-bayes-prediction-sg-hk
  annotations:
    scenarios.ai.sap.com/description: "naive-bayes serving Pipeline-sg-hk multi-market"
    scenarios.ai.sap.com/name: "naive-bayes-sg-hk"
    executables.ai.sap.com/description: "naive-bayes prediction-sg-hk"
    executables.ai.sap.com/name: "naive-bayes-prediction-sg-hk"
  labels:
    scenarios.ai.sap.com/id: "naive-bayes-sg-hk"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    artifacts:
      - name: multinomialNB_HongKong
      - name: multinomialNB_Singapore

  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: "{}"
      labels: "{\"ai.sap.com/resourcePlan\": \"starter\"}"
    spec: |
      predictor:
        minReplicas: 1
        maxReplicas: 2
        containers:
          - name: kserve-container
            image: docker.io/rahulcruze786/ml_prediction:v1.9
            ports:
              - containerPort: 8080
                protocol: TCP
            command: ["python", "app.py"]
            env:
              - name: STORAGE_URI
                value: "{{inputs.artifacts.multinomialNB_HongKong}}"
              - name: MODEL_PATH
                value: "/mnt/models"
              - name: PRIMARY_MARKET
                value: "Hong_Kong"
              - name: STORAGE_URI_Singapore
                value: "{{inputs.artifacts.multinomialNB_Singapore}}"
            resources:
              requests:
                cpu: "0.5"
                memory: "512Mi"
              limits:
                cpu: "1"
                memory: "1Gi"
